# Descomposición LU

In [1]:
import numpy as np

In [61]:
A = np.asarray([[1., 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [62]:
def Tij(a, i, j, n):
    assert j < i and i < n 
    X = np.eye(n)
    if j==0:
        X[i, j] = -X[i, i]/a
    else:
        pass

    return X

SyntaxError: invalid syntax (<ipython-input-62-8c0b2c438ca9>, line 4)

In [63]:
Tij(A[0,0], 1, 0, 3)

array([[ 1.,  0.,  0.],
       [-1.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [64]:
Tij(A[1,0], 1, 0, 3) @ A

array([[ 1.,  2.,  3.],
       [ 0., -3., -6.],
       [ 7.,  8.,  9.]])

In [65]:
Tij(A[2,0], 2, 0, 3) @ Tij(A[1,0], 1, 0, 3) @ A

array([[  1.,   2.,   3.],
       [  0.,  -3.,  -6.],
       [  0.,  -6., -12.]])

In [66]:
A_ = A
n = 3
print(A_)
for j in range(0, n):
    for i in range(j+1, n):
        print(i,j)
        a = A_[i, j]
        print('a:', a)
        A_ = Tij(a, i, j, 3) @ A_
        print(A_)
A_

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
1 0
a: 4.0
[[ 1.  2.  3.]
 [ 0. -3. -6.]
 [ 7.  8.  9.]]
2 0
a: 7.0
[[  1.   2.   3.]
 [  0.  -3.  -6.]
 [  0.  -6. -12.]]
2 1
a: -6.0
[[  1.   2.   3.]
 [  0.  -3.  -6.]
 [  0. -24. -48.]]


array([[  1.,   2.,   3.],
       [  0.,  -3.,  -6.],
       [  0., -24., -48.]])

In [67]:
def lu_decomposition(A):
    # Initialize L and U matrices
    n = len(A)
    L = [[0]*n for _ in range(n)]
    U = [[0]*n for _ in range(n)]

    # Compute L and U
    for i in range(n):
        for j in range(i, n):  # U
            U[i][j] = A[i][j] - sum(L[i][k]*U[k][j] for k in range(i))
        for j in range(i, n):  # L
            if i == j:
                L[i][i] = 1  # Diagonal as 1
            else:
                L[j][i] = (A[j][i] - sum(L[j][k]*U[k][i] for k in range(i))) / U[i][i]

    return L, U
    
L, U = lu_decomposition(A)

print("L: \n", L)
print("U: \n", U)

L: 
 [[1, 0, 0], [4.0, 1, 0], [7.0, 2.0, 1]]
U: 
 [[1.0, 2.0, 3.0], [0, -3.0, -6.0], [0, 0, 0.0]]


In [68]:
# Multiply L and U
LU = np.dot(L, U)

print("LU: \n", LU)
print("A: \n", A)

# Check if A and LU are equal within a tolerance
if np.allclose(A, LU):
    print("LU decomposition is valid")
else:
    print("LU decomposition is not valid")

LU: 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
A: 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
LU decomposition is valid


In [71]:

def lu(A):
    #source: https://johnfoster.pge.utexas.edu/numerical-methods-book/LinearAlgebra_LU.html
    #Get the number of rows
    n = A.shape[0]
    U = A.copy()
    L = np.eye(n, dtype=np.double)
    #Loop over rows
    for i in range(n):    
        #Eliminate entries below i with row operations 
        #on U and reverse the row operations to 
        #manipulate L
        factor = U[i+1:, i] / U[i, i]
        L[i+1:, i] = factor
        U[i+1:] -= factor[:, np.newaxis] * U[i]
    return L, U

L,U = lu(A)

In [73]:
L @ U

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])